// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdzhrmhwcyevnbnyjful.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkemhybWh3Y3lldm5ibnlqZnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzkyMzcsImV4cCI6MjA2NTUxNTIzN30.-8uvYHohWpa3wE0KDHR28A6W74uNe7KLhc5krr6L6wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);